spring:
  application:
    name: Lab2
  datasource:
    url: jdbc:mysql://172.17.18.6:3306/waaAssigDB?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: reconov
    password: reconov
#    password: ${DB_PASSWORD}
#    username: ${DB_USER}
  #    url: jdbc:mysql://localhost:3306/waa_assignmentDB?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
  #    username: 'root'
  #    password: 'password'
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
    show-sql: true
    defer-datasource-initialization: true
    generate-ddl: true
  sql:
    init:
      mode: always
  main:
    banner-mode: "off"
#    allow-circular-references: true

server:
  port: 4000

jwt:
  secret: 'someReallyComplicatedStringFromFileSomewhere'

#logging:
#  pattern:
#    console:

